### ISSUE TITLE
Sent packets not shown in candump

### ISSUE THREAD

**Issue by kevinsikes** [intrepidcs/intrepid-socketcan-kernel-module#11]
Using socketcan kernel module tag v2.0.5 (8a21b53) and icsscand tag v2.0.3 (c506f27), packets sent through ValueCAN are not shown in can-utils candump -- only received packets are shown.  If I use a different socketcan interface such as MCP2515, sent packets are shown correctly in candump.  Tested with ValueCAN 3 on Ubuntu 20.0.4.

**Comment by hollinsky-intrepid** [comment]
If you'd like an immediate fix, the two lines responsible for suppressing echos are [here in icsscand](https://github.com/intrepidcs/icsscand/blob/master/src/main.cpp#L273-274). Commenting them out will show transmitted messages as received.

I'll take a closer look at this. If I remember correctly echo is an option either on the network interface or the socket. Perhaps it's just something the MCP2515 driver sets as a default and we're not setting it, or the driver is responsible for implementing it.

**Comment by kevinsikes** [comment]
That did the trick -- thanks for the quick response!
