### ISSUE TITLE
Linux Kernel 6.4.6 breaks kernel module build

### ISSUE THREAD

**Issue by pottsdl** [intrepidcs/intrepid-socketcan-kernel-module#15]
Not sure specifically which Kernel update created the change in the "class_create" interface which used to take 2 arguments, and now only appears to take 1:

Old:
`	intrepid_dev_class = class_create(THIS_MODULE, INTREPID_CLASS_NAME);`

New:
`	intrepid_dev_class = class_create(INTREPID_CLASS_NAME);`

Will file PR with conditional for newer Kernel versions.

**Comment by kschwarz-intrepidcs** [comment]
Closed with 9caa973a5a986c5ca09866cec3ebca73870d0c54, thank you!
