### ISSUE TITLE
Kernel module not updated to check for newer User Daemon (icsscand) version

### ISSUE THREAD

**Issue by pottsdl** [intrepidcs/intrepid-socketcan-kernel-module#17]
This issue was originally covered on the icsscand side[ Issue 11](https://github.com/intrepidcs/icsscand/issues/11).

It appears that the Kernel module version checking wasn't updated after commit f67b4b3 to increase the maximum number of devices to 64.  It still is checking against 3.0.x.

Filing a PR to address the check against 3.0.x, to now be 3.1.x (that might still be wrong) and to use the KO_MAJOR, KO_MINOR constants instead of hard coded values (which were missed last time).

**Comment by kschwarz-intrepidcs** [comment]
Thank for for the report, this has been resolved with 67c196ddfe4f7a8aea4f0b4a82a739fe82da620d
