### ISSUE TITLE
LEDs are not blinking on ValueCAN3

### ISSUE THREAD

**Issue by tysonite** [intrepidcs/intrepid-socketcan-kernel-module#6]
1. When we use ValueCan3 with amrbian built with 4.13.15-sunxi kernel and intrepid software is built with following revisions, we see that LEDs are working fine. ValueCan4 is not supported in this case by intrepid software.

https://github.com/intrepidcs/intrepid-socketcan-kernel-module  d8ea05895e3fc1ec16f0444401f763beb20b6fdd
https://github.com/intrepidcs/icsscand  9fde92fa4030d6693d61c9189bf9db04307718cb
https://github.com/intrepidcs/icsneoapi  694bf94eeaed933aabc6ea417be5d1cfe32d06a1

2. When we use ValueCan3 with armbian built with 4.19.50-sunxi kernel (we had to upgrade kernel to make newer versions of intrepid software compilable), then LEDs are not working at all, but CAN messages are actually coming (we can send from host and receive them). If we use ValueCan4 in the same setup here, then LEDs work fine. Following intrepid versions are used in this case:

https://github.com/intrepidcs/intrepid-socketcan-kernel-module  7c2583c938c74f11e99f005a7cbab4802c9a3b46
https://github.com/intrepidcs/icsscand  318af6b4f395cb2ba97e7d20b57d0944c0c905f5
https://github.com/intrepidcs/icsneoapi  694bf94eeaed933aabc6ea417be5d1cfe32d06a1

**Comment by hollinsky-intrepid** [comment]
Hi tysonite,

https://github.com/intrepidcs/icsneoapi is now deprecated, and is no longer used by the latest https://github.com/intrepidcs/icsscand. Now, building https://github.com/intrepidcs/icsscand will inherently build https://github.com/intrepidcs/libicsneo into it.

https://github.com/intrepidcs/libicsneo is our new fully featured open source device communication API, completely superceeding the https://github.com/intrepidcs/icsneoapi. All features from the old API are now implemented in the new one.

The new device communication API is most likely where the bug exists for ValueCAN 3, so I'm making the bug report https://github.com/intrepidcs/libicsneo/issues/16 and closing this one. The bug should only affect the LEDs and should not affect other device functionality.

Let us know if you need anything else!

--Paul
